---
baseURL: "/"
title: "doc"
theme: "hugo-mc-docs"
# ignoreFiles:
#   - "\\.foo$"
defaultContentLanguage: fr
languageCode: "fr-FR"
buildDrafts: true
uglyURLs: false
canonifyurls: true
taxonomies:
  category: "categories"
  tag: "tags"
params:
  brand: "Makina Corpus"
  organizationname: "Makina Corpus"
  sitedescription: "docs"
  release: "1"
  description: "documentation"
  logo: "/images/MakinaCorpus_logo_vert_blanc.svg"
  favicon: "favicon.ico"
  siteaddress: "https://foo.net"
  ghrepo: "https://gitlab.foo.net/doc/umentation/"
  ghdocsrepo: "https://gitlab.foo.net/doc/umentation/edit/master/"
  permalink: "#"
  includejq: false
  sitepublishdate: ""
  twitterhandle: null
  facebook: null
  defaultsocialimage: null
  removefromexternalsearch: true
  ghdocswiki: null
  ghdevwiki: null
  gitter: null
  forum: null
  gtmid: ""
  # Set to true to include a CDN call to FontAwesome
  # (note that Hugo docs currently hosts its own FA
  # (see pipeline/scss/_variables.scss))
  usefontawesome: false
PygmentsCodeFencesGuessSyntax: true
PygmentsCodeFences: true
pygmentsUseClasses: true
# disableKinds = ["page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]
PygmentsCodeFencesGuessSyntax: true
PygmentsCodeFences: true
pygmentsUseClasses: true
disablePathToLower: false
disableLiveReload: false
disableRSS: false
disableSitemap: false
enableGitInfo: true
enableRobotsTXT: true
disable404: false
disableHugoGeneratorInject: true
enableEmoji: true
verbose: true
verboseLog: true
hrefTargetBlank: true
blackfriday:
  hardLineBreak: true
  footnotes: true
  definitionLists: true
  fencedCode: true
  tables: true
  smartypants: true
  fractions: true
  smartDashes: true
  plainIDAnchors: true
# This intelligently adds an "s" to the titles of list pages
pluralizelisttitles: false
preserveTaxonomyNames: true
watch: true
metaDataFormat: "yaml"
permalinks:
  temp: "/:title"
menu:
  main:
    - URL: /
      Name: "Home"
      identifier: home
      weight: 1000
    - URL: /sectiona/
      identifier: sectiona
      Name: "A section"
      weight: 2000
    - URL: /sectionb/
      identifier: sectionb
      Name: "B section"
      weight: 3000
    - URL: /sectionc/
      identifier: sectionc
      Name: "C section"
      weight: 4000
    - URL: /sectiond/
      identifier: sectiond
      Name: "D section"
      weight: 3000
    - URL: /sectione/
      identifier: sectione
      Name: "E section"
      weight: 3000
    - URL: /contribute/
      Name: "Contribute"
      identifier: contribute
      weight: 1000
---
# vim: set et:
